### ISSUE TITLE
Cerbu malware detected

### ISSUE THREAD

**Issue by PaszaVonPomiot** [Shampra/EvernoteToAnytype#10]
![image](https://github.com/Shampra/EvernoteToAnytype/assets/5560454/62b30ccb-afe4-4471-bcbf-f7e0d940637b)

**Comment by Shampra** [comment]
It's due to your version of Pyinstaller.  
pyinstaller/pyinstaller#8164  
Some antivirus doesn't like python packager tools like Pyinstaller.  
You can try another version of Pyinstaller.

**Comment by Shampra** [comment]
Last version seems OK for Bitdefender .
![image](https://github.com/Shampra/EvernoteToAnytype/assets/16141040/aa336caa-3743-4650-bf3b-d6f6127b186f)
