### ISSUE TITLE
Stuck on converting 1 simple text note

### ISSUE THREAD

**Issue by PaszaVonPomiot** [Shampra/EvernoteToAnytype#2]
v0.8

Single note exported from Evernote without tags added to this tool and clicked to convert. Stuck on below message.

```
('C:/Users/xxx/Desktop/EVER_EXPORT/1.enex',)
['C:\\Users\\xxx\\Desktop\\EVER_EXPORT\\1.enex']
Conversion de 1.enex...
```

**Comment by Shampra** [comment]
Correction add in 0.8.2
Can you try again?
